language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - cd sg-angular
  - npm install -g @angular/cli
  - npm install @angular-devkit/build-angular

script:
- cd ..
- npm link
- cd sg-angular
- ng build